### ISSUE TITLE
test18 regression - 'shared' function argument not translated

### ISSUE THREAD

**Issue by nenadv** [Intrepid/upc2c#41]
After the update to 3.4 baseline test18 gets an error:

test18.trans.c:243:18: error: unknown type name 'shared'

Here is a sample code:

```
void
bug230_proc(strict shared int ia[2][10*THREADS])
{
   ia[0][0] = 1;
}
```

is translated into

```
void bug230_proc(shared strict int (*ia)[10*THREADS]) {
    UPCR_BEGIN_FUNCTION();
    int _bupc_spilld0;
    {
        (_bupc_spilld0 = 1 , UPCR_PUT_PSHARED_STRICT(UPCR_ADD_PSHARED1(UPCR_ADD_PSHARED1(ia, 4UL, (0 * (10UL * upcr_threads()))), 4UL, 0), 0UL, &_bupc_spilld0, 4UL) , _bupc_spilld0);
    }
}
```
